lib/reference.coffee
I've seen reference items send users to welcome-visitors. This is the default if the reference doesn't have a slug for the referenced page. I don't know when this started happening but I'm seeing lots of references without slugs. Perhaps the revision to the drop logic let this one slip in.
I've added a fall-back to making the slug from the title if title is present. This restores the desired behavior if by an alternate means. I'm deep in another set of commits or I would track down the root cause.
=> try harder to find a reference slug

Gruntfile.js, lib/editor.coffee, lib/paragraph.coffee, lib/reference.coffee, lib/refresh.coffee, lib/resolve.coffee, test/resolve.coffee
These commits improve html escapes as suggested in issue #80.
(Somehow I've picked up an independent commit appearing in a separate pull request.)
We combine resolving links with escaping html. The link resolution happens in two steps with the html escaping occurring between them. This is the comment from the relevant code.
```
```
The resolveLinks call now takes a second parameter where one might provide an alternative to simple html escaping. Alternative markup plugins will use this to offer their alternative translation method. The method provided must be secure in that it must effectively escape in addition to what ever else it does. There will be companion pull requests to these plugins that should be released together.
We also escape the page title text. This is step two of closing …
=> Improved html escapes now handled by resolveLinks

lib/page.coffee, lib/refresh.coffee
This commit adds logic to the item drop handler to assign a new id to any item that conflicts with any existing item with the same id. This conflict happens when dragging multiple copies of an item into a single page.
This can happen when pulling items out of history. You can keep recalling the item from history and keep pulling the recalled item on to the same page. Move depends on unique ids and probably other things too.
The original id will be restored if the aliased item is subsequently dragged to a page without id conflict.
Journal merge will have to deal with similar aliasing if it is to be reliable.
Items that have been aliased store their original id in a field named 'alias'. Yes, I know this is counter intuitive.
=> save true item.id as item.alias to avoid duplicates

lib/legacy.coffee, lib/page.coffee, lib/pageHandler.coffee, lib/refresh.coffee, lib/search.coffee
This pull request replaces the hopelessly convoluted incremental pageHandler.put logic that is engaged when a pages is automatically forked to local storage. This uses the newish pageObject as the trusted representation to be saved (the product of our core client refactoring) along with emitting a 'refresh' event that communicates from the bowels of storage to the user interface, the first that we've employed this long-sought approach.
With this we need not fear the "yellow halo of doom" as it has become known.
The previously serious deficiency is now replaced with several known inconveniences.
* The textEditor split logic is foiled by the 'refresh' and reverts to the same behavior as other item types.
* A shared memory bug causes some history loss in the journal with repeated edits.
We …
=> Improved put logic makes editing in localStorage viable.

client.coffee, lib/addToJournal.coffee, lib/refresh.coffee
This is a start of what we talked about in the hangout (Feb. 4th 2015).
Links and events that that would result in a change of origin will open in a new tab. We use the site name to name the tabs, so we can reuse tabs.
Works well in Chrome (and Vivaldi), but in Firefox the initial tab does not get reused correctly - suspect this is a browser feature.
While focus is switched, correctly in Chrome, it does not work correctly in Firefox if it configured to open new windows in a new tab.
=> a single tab per origin

lib/legacy.coffee, lib/target.coffee
This pull request improves the item/action hover logic several ways.
* The hover highlight and scroll effects require that the shift key be pressed.
* Shift will highlight immediately when already hovering.
* Highlight state (class .target) is set and cleared rather than toggled avoiding sync problems.
* Hover over events highlights and scrolls other pages.
The scroll positioning would be better if it aligned like items on item hover. This has many boundary conditions that I will explore and then submit in a later pull request.
=> Shift for hover effects on items and actions.

lib/page.coffee, lib/refresh.coffee, lib/revision.coffee
We've seen trouble rendering items cascade backwards through successfully rendered items. We're traced this to unexpected null items in a story. This pull request makes rendering of both items and actions more tolerant of nulls by carrying on as best as can be expected.
=> tolerate nulls for items and actions

lib/pageHandler.coffee
The pageHandler rewrites the dom of a page when forked so that it appears to have come from the origin. This commit revises this logic to make an acceptable href for the page's flag.
This commit addresses the issue raised in https://github.com/fedwiki/wiki-node/issues/44 where a recently forked page could not be dropped on a Factory with expected result.
=> correct page flag's href after fork

client/style.css, lib/pageHandler.coffee
This corrects a formatting problem exposed by https://github.com/fedwiki/wiki-node/issues/45.
Formatting could be improved but this at least corrects the regression.
=> html formatted error message now requires html plugin

lib/addToJournal.coffee
Paired with @WardCunningham to add the site location to the hover effect in the journal, for actions that have an associated site.
=> Add site name mouse over to forks in journal

lib/factory.coffee
This pull request is for the feature discussed in issue #117.
We stop short of reading or revising EXIF metadata. This leads to some drops appearing sideways.
=> Resize and compress large images on drop.

client/style.css
This PR adds imitates github styles for `<code>` and `<blockquote>` elements.
This is needed for the `wiki-plugin-markdown` but other plugins can benefit of these styles as well.
=> Add styles for inline code and blockquotes

lib/paragraph.coffee
Wiki shortens slightly the path to making Paragraphs over other item types. This pull requests extends slightly the shift-double-click hack that converts Paragraphs to the now sanitized HTML type by considering alternatives.
Shift-double-click now inspects the Paragraph for the presence of various tags before converting to HTML. If absent, the converted item will be type Markdown instead. This is the list of expected tags extracted from the regular expression used to perform the test.
```
(i|b|p|a|h\d|hr|br|li|img|div|span|table|blockquote)
```
=> shift-double-click for html or markdown

lib/importer.coffee, lib/legacy.coffee, lib/link.coffee, lib/page.coffee, lib/plugins.coffee
The server will bundle all site pages into an export file easily downloaded into a single file. [json](http://divergence.hapgood.net/system/export.json)
This pull request implements a simple way to recover individual pages from such a backup.
* Users export their sites to their own computer for backup.
* To recover a page, simply drag the backup file into the wiki tab.
* A ghost page opens listing the contents of the backup.
* Click any title to see the backup version as another ghost page.
* If it is the wanted page, fork it over your mistake.
This is what it might look like while recovering an accidentally damaged welcome page. Notice that both pages are ghostly because they do not yet exist in the site. The welcome page will turn white if forked.
We use the existing fork mechanism on …
=> Drag and drop to import from export files

lib/factory.coffee
This information is logged in the action and available by double-clicking the timestamp.
=> record more useful info when file drop fails

lib/neighborhood.coffee
This changes the delay between loading sitemaps to 1/2 second. Let's make this 4x improvement the norm. This builds on @paul90's months of improvements to sitemap caching and now activity configuration and rendering.
=> speed up sitemap loading by 4x

lib/plugin.coffee
We catch errors when rendering plugins and offer help. However, the exception prevents further emit/bind logic, so we find ourselves without the ability to correct simple markup errors.
This pull request adds markup editing even when a plugin doesn't show.
This is especially useful to plugin developers who haven't yet developed their own input validation to prevents a new plugin from throwing errors.
=> edit item.text even when a plugin won't show

lib/legacy.coffee, lib/refresh.coffee
This experimental feature is not ready to be merged.
This commit adds a link to a search choice page in the footer of every wiki page.
The link opens a ghost page offering three different searches.
This represents one component of a larger search project.
http://ward.asia.wiki.org/about-search-plugin.html
http://ward.asia.wiki.org/distributed-search.html
=> add footer link to search choice ghost page

lib/legacy.coffee
We correct a confusing bug where transported pages appear as ghosts but do not lose the ghostly appearance when forked into the origin site. 
We move the ghost-class removal code used when forking from history so that it is applied in all forking cases. No fork ever produces a ghost page.
@opn brought this bug to my attention.
=> lose the ghost flag whenever page forked

Gruntfile.js, client/style.css, lib/link.coffee, lib/page.coffee, lib/refresh.coffee
- This adds a new div called "paper" that contains the scrollable viewport instead of the page.
- Adds a "asTitle" utility method to convert a slug back into a title.
@WardCunningham will check this out for a bit with the various plugins to ensure it doesn't break anything.
=> Add a paper scrollable div inside the pages viewport

client/style.css
Fixes #144 by moving the width definition from `.page` to `.paper`
=> move width from page to paper

views/static.html
Handlebars 4.x added the escaping of `=`
This fixes fedwiki/wiki-server#117
=> prevent origin from being escaped

client/style.css
prevents bottom box-shadow from appearing partway up page on short pages.
:blush: didn't spot the problem with short pages until after #145 was merged.
=> set a minimum height on .paper

client/style.css, lib/editor.coffee, lib/legacy.coffee, lib/refresh.coffee
The .local, .remote and .plugin classes are added to .page divs to add halos and sometimes control behavior. This commit reverses the decision to move this annotation to the recently introduced .page child div.paper which is the medium that scrolls.
Rather than move the annotation, we style the .paper using the css combinator: child selector, denoted by the greater-than arrow. For example, this selector will style the .paper of a .remote page.
```
.page.remote > .paper { ... }
```
Regretfully v0.7.3 was published with css changes that were incompatible with our current .page.local and .page.plugin machinery thus omitting halos in these cases. Here all halos are visible.
=> style .paper from classes on parent .page

client/style.css
This commit corrects two problems observed since we've introduced .paper to carry the colored halo.
* Pages were slightly larger than the div that held them. This meant they could wobble side to side by a few pixels.
* Page width was unconstrained on page load until javascript rewrote the page with the .paper div added.
=> move width from .paper to .page

client/style.css, lib/reference.coffee
I'd like to make a page of References look a little better, more like natural text. We started coloring them so that one would see the first line and subsequent lines as one thing. Let's just merge subsequent lines onto the end of the first line so it does look like one thing even if not given any color treatment.
=> simplify reference styling

lib/refresh.coffee
Pull request #155 will pass the create action that made a page to the Future plugin when that link goes nowhere. Looking for the offending link is the search before the search.
With this commit we handle the case where the first search fails. A good example of where this happens is when one clicks on an axis label of the Radar chart.
=> guard against case where link has not been found

lib/factory.coffee
Ward and myself looked into this *old* bug, where when creating an item it ends up being scrolled off to one side.
=> preventing the horizontal scroll to unexpected places on creating item from factory

lib/neighborhood.coffee, lib/page.coffee, lib/pageHandler.coffee
Search can't find pages that were just added to a site because the sitemap is out of date. This pull request updates the sitemap for the origin on each successful page put.
This inaccuracy is especially annoying for the Graph plugin when clicks create new pages without changing the color code, green should turn to blue. Here I added Random Page to the RSP graph and then clicked it. I was asked if I wanted to create the page. See that it has turned blue when I clicked the create button in the adjacent Future page.
=> update local sitemap on each put

client/style.css
This addresses a long-standing limitation wherein journal action background gradients were assumed to be gradients and of the dimensions of generated gradients. (I waited for the avatar style backgrounds to go away and even created the Flagmatic plugin to offer some choice within federated wiki branding. But good content remains with poorly rendered backgrounds.)
Consider:
http://journal.hapgood.net/artwork-as-recipe.html
Before:
After:
Notice that even the generated gradients look better since they too are sized and rendered in full.
=> size the action background gradient if it is other than expected

client/style.css, views/static.html
These are small changes that make display more consistent between narrow windows, small screens, and non-javascript tabs.
* Change title to Federated Wiki, omitting the word Smallest.
* Add div paper to static html to remove jarring visual effect on first load.
* Adjust thresholds and margins for smoother responsive behavior.
=> static html, css improvements

views/static.html
This pull request exploits the server improvements here:
https://github.com/fedwiki/wiki-server/pull/120
This will encourage other services to use the proper page title when referring to wiki pages, for example `Federated Timeline` instead of `Smallest Federated Wiki` in the example below.
=> use proper title in .html version

lib/drop.coffee, test/drop.coffee
A reworking of the drop video handling.
Rather than performing a series of regular expressions this code uses node's `url.parse` to separate the part of the URL and switch on the `hostname` from the dropped URL.
Tests are also added.
=> updating video drop handler, and adding tests

.travis.yml, package.json
Update dependencies
Node.js v0.10 is now out of support, with v0.12 following at the end of the year. Update to reflect this.
=> Stop testing Node.js 0.10, and increase minimum version supported to 4.x

client/style/style.css
Recent chrome browsers will inappropriately add a scrollbar to the journal upon hover over the the add or fork buttons when they are alone on the last line. (Firefox does not exhibit this unwanted behavior.)
This case is easy to duplicate by retrieving from history a revision where this is true. 
The fix is to restore some padding that was removed with the introduction of the .paper div. This leaves room for the hover effects which must be of box dimensions that round differently between chrome and firefox.
=> padding to stop jitter on button hover

lib/resolve.coffee
We depend on slugs to give us case insensitivity. That is [[Welcome Visitors]] and [[welcome visitors]] link to the same page. We also get a sometimes unwanted insensitivity to all non-alphanumeric characters.
This pull request refuses to link to a title with no alphanumeric characters. This avoids the case where there the link slug would be empty. We don't yet consider the case where the slug is non-empty but stripped of useful identifying unicode characters.
This improvement based on conversation on matrix:
https://riot.im/app/#/room/#fedwiki:matrix.org/$14842628142654GcOwU:matrix.allmende.io
=> ignore links with empty slugs

lib/addToJournal.coffee, lib/factory.coffee, lib/lineupActivity.coffee, lib/link.coffee, lib/neighborhood.coffee, lib/neighbors.coffee, lib/page.coffee, lib/pageHandler.coffee, lib/reference.coffee, lib/refresh.coffee, lib/siteAdapter.coffee, lib/wiki.coffee, test/page.coffee
This approach is one that @WardCunningham and myself discussed over on Sunday.
The problems with the previous prototypes start when we request a flag, and don't yet know how to construct the request for it. Determining how to correctly connect to a remote site is asynchronous, which forces get the flag's URL into being asynchronous, which then ripples back through the client.
Here, rather than determine the form of the URL for the flag, if we don't already know how to construct its URL we create a temporary flag, which we will use for the remote site until know to construct the request for the remote site. Once we know the URL for a remote site's flag, we will replace its temporary flag with the real one.
The first commit here will just use a temporary grayscale gradient flag for a remote …
=> site adapter prototype - just flag and get

lib/editor.coffee, lib/legacy.coffee, lib/refresh.coffee, package.json
This pull request is a variation of wiki@next that makes wiki editing optional.
Here with `wiki` not selected. Drag just selects text. No journal or action buttons.
Click `wiki` in the footer to restore normal wiki edit operations.
=> toggle wiki editing

lib/siteAdapter.coffee, package.json
When we find that a site is unreachable (down?) in findAdapter we set the prefix to `""`. However when we try and get an item from that page we didn't use the callback correctly.
Here we set `status` so the code calling making the call can handle the site not being present correctly.
This fixes #189
=> site unreachable?

lib/legacy.coffee
In an earlier comment I noted that toggling read-write would cause an unwanted accumulation in the lineup model. https://github.com/fedwiki/wiki-client/pull/187#issuecomment-291378581
I've tracked this problem down to a call into lib/refresh at too high a level. The lineup is intact so we should instead just rebuild the dom $page from available information. There is an entry point for exactly this purpose and a sample call a little higher in the code where the page `create` button rebuilds an existing (ghost) page.
```
.delegate 'button.create', 'click', (e) -> ...
```
=> rebuild existing pages on toggle wiki

lib/editor.coffee
We prevent the default alt-s handling when saving edits. This commit mimics the adjacent alt-i handling. This seems harmless and safe to merge even though it has not yet been tested on the device where the unwanted event propagation issue was reported, #183.
@cliveb
=> prevent default for alt-s

client/style/style.css, lib/legacy.coffee, lib/neighborhood.coffee, lib/page.coffee, lib/pageHandler.coffee, lib/refresh.coffee, lib/siteAdapter.coffee, lib/wiki.coffee
Work in progress. See checklist below.
After six years, finally working on delete command. To delete a page, recall its creation with no content, then fork that to the server. New logic interprets forking a page with no contents as delete. (This is like saving a Paragraph with no text to delete it.)
After a successful server-side DELETE, the page appears as it did before it was created. The create action in the future journal is new but preserves some parameters from the old such as the Transporter continuation logic, if any.
So far we have discovered and addressed many client-side issues while simulating server side delete in pageHandler.delete with a timer and fixed value for err status. We either delete the file with a shell command or just reload to discover that the deleted page has …
=> detect and process page delete

lib/synopsis.coffee
We take the first paragraph of the candidate synopsis, and then reduce it to the first 560 characters.
This is a proposed fix for fedwiki/wiki-server#136
=> More concise synopsis.

lib/refresh.coffee
Fix for issue #202 
When pageHandler can't find a page the refresh logic builds a Future as substitute. This logic looks for the internal link from which to recover the proper title. This commit revises the jquery selector used to be specific that it wants links of class .internal  so that any intervening pages with the same link in its flag does not confuse the logic.
Thanks go to @opn for recognizing the repeatable case.
=> be specific looking for internal link text

lib/editor.coffee
Type cmd/alt-m to return to plugin menu.
- recognized during edit only
- menu does not erase text, returns to text editor on most selections
- further text change required to persist choice
Typical workflow:
- recognize preferred plugin while editing
- cmd/alt-m to select desired plugin
- continue editing then cmd/alt-s to save
Preferred mechanism for adding captions to images:
- split into the editor
- write the desired caption
- cmd/alt-m to return to menu
- drop image on the menu
=> simple alt-m handler, might be best

lib/refresh.coffee
This makes a difference in the appearance of tab-sequence highlights.
Without this change:
With this change:
=> avoid trailing space in flag anchor

client/style/print.css
Sometimes our short paragraphs and narrow column spill ungracefully onto the printed page. Better to add broad margins and retain some approximation of the online look.
Becomes:
From the original:
=> wide margins for print

lib/legacy.coffee, lib/neighborhood.coffee, lib/neighbors.coffee, lib/siteAdapter.coffee, package.json
Here we switch to using a queue to prevent overloading the browser, or a remote server, and using ajax to GET the image which allows us to detect any redirects that will cause problems later in the flow.
=> Change the site adapter discovery mechanism

lib/pageHandler.coffee
We allow edits to about pages which get stored as normal pages as if they were forked from a remote site. We have always meant for the green halo to be removed when this happens but have never made that so until now.
This proper signaling of page location becomes more important because a user can now easily delete the unwanted copy revealing again the distributed plugin documentation.
We don't record implicit forks of about pages. This leaves the Journal a bit cleaner when a plugin author uses this means for revising documentation. Debug and write in the same server then copy pages back to the plugin source before commit.
```
cp ~/.wiki/localhost/pages/about-some-plugin pages
```
=> remove green halo when forking about pages

lib/image.coffee
The original `gateway` would never work with sites that are hosted from https
The `gateway` value is changed to specify the protocol `http:` and change `localhost` to `127.0.0.1`
We have to use an IP address, rather than `localhost` to avoid content getting blocked with a mixed content warning.
=> change IPFS gateway so it has a chance of working from https origins

lib/addToJournal.coffee, lib/page.coffee, lib/refresh.coffee, lib/siteAdapter.coffee, test/page.coffee
We extend the site adapter to add `getDirectURL` which gives us the URL to use where a resource is going to be directly accessed, typically used when opening a new window; keeping `getURL` to construct the URL where we are going to access it programatically.
We also update the site adapter so that saved adapter configuration is loaded at start-up.
This is linked with correctly supporting https origins with WardCunningham/wiki-plugin-assets#3
=> asset plugin

lib/legacy.coffee, lib/license.coffee, lib/refresh.coffee
@opn reminds us that the attribution from forks in the journal is hidden in read-only mode and no attempt has been made to explain sources entering by transporter.
Here we intercept the previously supplied link to Creative Commons and offer our interpretation of the journal in the context of our chosen license.
We look for non-fork actions and report the sites that they appear to originate at based on subsequent forks or the ultimate owner of the page.
We look for "provenance" attached to the first action (typically a Create) and render that as wiki text when present. Here I edit .wiki/localhost/pages/welcome-visitors to test this feature.
```
"journal": [
{
"type": "create",
"item": {
"title": "Welcome Visitors",
"story": []
},
"date": 1420938191608,
"provenance": "This page provided by …
```
=> add license details to page footer license link

lib/siteAdapter.coffee
`done` should only be called once, either in `getContent`, or in the else part of the condition.
This correct an error where done is getting called too soon, on the fall through, rather as part of the call back from getContent.
=> stop fall through

lib/legacy.coffee
This seems so obvious but I can't get it to show by adding a revised wiki-client to my localhost server. There should be one more option in this panel.
=> add slug search to wiki page footer search options

client/style/style.css, lib/active.coffee, lib/link.coffee, views/static.html
When changing the active page with the left / right arrow keys, the keyboard focus doesn't follow which makes it impossible to scroll the new active page without using the mouse.
This small change enables the page div to be focusable (by setting the tabindex) and then uses this new ability to set the keyboard focus whenever a page is made active.
I chose a tabindex of -1 so pages aren't added to the list of tab selectable elements.
=> Set tabindex of pages and focus them when active.

lib/editor.coffee
This fixes an issue caused by PR #231. When you click in an already active editor to reposition the cursor, the click event propagates up to the parent which calls active.set() which causes the active editor to lose the focus when focus is called on the page.
Here are the ways I can see this issue could be fixed. (This PR goes with option 1):
1. Tell the editor to not allow the event to propagate to the parent.
2. In active.set() change the call to only call focus if there is no element with the .textEditing style present in the DOM.
3. In active.set() don't call focus if the to be activated page is the currently active page.
Options 2 and 3 feel like they are trying to undo something that should not have happened. Option 1 is the only one that prevents the problem from happening in the …
=> Don't propagate editor click events to page.

lib/active.coffee, lib/editor.coffee, lib/legacy.coffee
Fixes #233 
Changes to how we set page focus, so that it is only done after the page scrolling animation is complete (to prevent flicker), and if focus is not already set within the current wiki page.
=> Prevent flicker and loss of focus from wiki page elements during lineup scrolling

test/neighborhood.coffee, test/page.coffee, test/pageHandler.coffee, test/refresh.coffee, test/search.coffee
For some reason this was over looked when the siteAdapter was created. Here we add mocking of the siteAdapter calls, so that the existing tests run.
=> Restore browser test page

client/style/style.css, lib/active.coffee, lib/legacy.coffee, lib/lineup.coffee, lib/refresh.coffee, lib/state.coffee
This PR enables pages to be reorder by dragging them. The URL is updated to the new lineup once a page has been dropped.
A couple of implementation notes:
* I was unable to find a way to prevent the user from dragging infinitely to the right. After the first checkin, it was possible to be stranded on the far right without any way to scroll back to content. The second checkin fixes that by scrolling the dropped page back into view.
* A new parameter was added to active.set to allow the active page to be set without immediately scrolling to it. This prevents some odd scrolling back and forth scrolling behaviors in longer lineups where pages are partially obscured.
A desired future addition is to allow pages to be removed by swiping up or down. That may change some of the implementation …
=> Drag to reorder pages

lib/siteAdapter.coffee
Paired with @WardCunningham on this.
We are using the returned jquery ajax promises in wiki-plugin-graphviz, this PR makes it unnecessary to pass in a dummy callback, and makes all siteAdapter get methods work with promises the same way the graphviz plugin assumes they do.
=> site adapter promises

lib/editor.coffee
Request from the group in Dayton to allow ESC to be used to close editors in addition to the current cmd/alt-s key combination.
=> Allow ESC to save editor.

lib/editor.coffee
This PR removes the use of the alt key combinations to perform actions on a page item. This allows for these key combinations to revert to their expected behaviour of providing keyboard access to alternative characters.
=> remove altKey combinations

lib/editor.coffee
After the removal of alt key support in PR #240, I was unable to figure out how to change the type of an item as I used to use alt-m. After looking at the source, I discovered the problem. e.ctlKey is undefined. It needs to be e.ctrlKey.
=> Fix typo in ctrlKey modifier.

client/style/style.css, lib/refresh.coffee
This PR changes the mouse cursor when reordering items within a page or moving / copying between pages based. They also give the user some visual feedback when performing a copy.
These changes likely need some burn in time before they can be committed. I'm starting the PR now to get feedback and gives others the opportunity to try them out. I don't have them hosted anywhere at the moment. I may need to spend some time tweaking my hosting setup so I can host different wikis running different versions of the codebase. I'm limited to one-ish right now.
Changes:
* Use the copy cursor when shift is held down.
* When the copy cursor is shown, show the original item on the source page.
* Use the move cursor by default.
* Do not show the copy cursor when on source page.
* Tweak mouse offset on …
=> Rework copy and move item user experience.

lib/wiki.coffee
We hold page json as js object in two places, `$page.data('data')` and in pageObjects in the lineup. The later is the preferred version but it turns out neither are updated as pages are edited. Here we make the singleton lineup available to plugins so that pageObjects become available and can benefit from anticipated improvements.
With this change the few places that require accurate page json will use 
```
wiki.lineup.atKey($page.data('key'))
```
which will eventually be maintained consistent with the server.
With this change in mind we examine where we might assume that pageObject is already kept current. It turns out not many places but there could be more.
- Legacy: show page source, revision
- Future: some crazy logic that will return to a transporter for more content
- License: some …
=> expose lineup so plugins can access models

lib/plugin.coffee
This PR resolves a race condition which was leading to plugins getting loaded multiple times. Promises are a really nice fit here. Eric is going to build on this to add support for plugins that use ES6 modules.
The changes are live on fed.wiki.randombits.xyz if you want to take a look.
FYI: @WardCunningham, @paul90, @dobbs.
=> Prevent duplicate plugin loads using promises

lib/resolve.coffee
We can't be sure that page json is well formed. Instead we must make safe assumptions when we find unexpected nulls or undefined. 
```
wiki-client/lib/resolve.coffee:58
string = string.replace(/〖(\d+)〗/g, "〖 $1 〗")...
TypeError: Cannot read property 'replace' of undefined
```
=> guard against nulls

lib/refresh.coffee
When code was added to allow item drag operations to be cancelled by pressing escape, it inadvertently broke the ability to copy items between pages.
This PR properly guards the setting of the `dragCancelled` flag so it only happens when escape is pressed.
=> Only cancel drag if escape is pressed.

client/style/style.css, lib/legacy.coffee, lib/refresh.coffee
When reordering pages, it is sometimes possible to get the page to drop onto the journal of an adjacent page. The easiest way to reproduce this is to scroll down so a large journal is visible and then drag another page across the page with the large journal. The large journal will get a small outline when it is the drop target. If you drop the page at this point, the page freezes (example screenshot below).
This is the error that appear in the JavaScript console.
```
client.max.js:2714 Uncaught TypeError: Cannot read property 'getRawPage' of undefined
at Object.merge (client.max.js:2714)
at HTMLDivElement.j (client.max.js:3630)
at e.<computed>.<computed>._trigger (jquery-ui.min.js:6)
at e.<computed>.<computed>._drop (jquery-ui.min.js:7)
at e.<computed>.<computed>._drop …
```
=> Prevent page from being dropped on a journal

.gitignore, Gruntfile.js, client/style/style.css, lib/editor.coffee, lib/forward.js, lib/legacy.coffee, lib/link.coffee, lib/page.coffee, lib/plugin.coffee, lib/plugins.coffee, lib/refresh.coffee, lib/target.coffee, package.json
This PR makes a lot of changes.
* On initial page load plugin emits are done in parallel, but binds are done serially.
* Holding shift when hovering over items that consume other plugins will put an orange highlight around the consumed items (this requires plugin authors to add a `.consumed` attribute to their dom elements).
* Handle updating plugins that consume other plugins whenever a notable event occurs which includes:
1. When an item is added
1. When an item is removed
1. When a page is opened
1. When a page is removed
1. When an item moves in the lineup
1. When a page moved in the lineup
1. When an item changes type
* Removes .js files from the `.gitignore` as there is now a javascript file in lib.
* Switches from uglify to uglify-es as the javascript file uses ES6 syntax.
* Fixes …
=> Order plugin bind operations based on declared dependencies

client/style/style.css, lib/plugin.coffee, lib/target.coffee
This PR reduces the requirements on plugin authors while also making the system easier to debug.
Prior to these changes, plugin authors had to remember to put a `consuming` property on their items as part of their bind. This was a manual, error prone process.
After this change, the bind wrapper in plugin takes care of this for them, but there is a slight difference in behavior.
The old behavior only tagged an item as consumed after it was consumed. The new behavior tags an item as consumed the moment something else is waiting on it. Without this change, it isn't possible to highlight what is blocking the bind of the items highlighted in red. With this change, shift hovering over an item in red will highlight in orange the items being consumed. At least one of those highlighted in orange …
=> Highlight items when their bind is blocked

lib/editor.coffee, lib/plugin.coffee
When pressing enter in an editor, a new editor usually opens. With the most recent changes, this breaks.
This PR removes what appears to be an unnecessary call to `plugin.do`. That call is asynchronous and rerenders the lineup which stomps on the editor that is created right after the call.
It also calls `.off()` before rendering an item. This cleans up any event handlers previously attached to the item itself.
=> Fix pressing enter to create new editors and clean up event handlers

lib/plugin.coffee
This is an odd defect.
When changing item types, the list of consumed items isn't cleared if the new item type doesn't consume anything. This makes it possible to make a `paragraph` look like it is consuming a `diag`. You do this by putting two diags next to each other and then changing the type of the second one to a paragraph.
=> Clear previous 'consuming' list during bind

lib/siteAdapter.coffee
This prevents an unhandled promise error message in the log. From #237.
Mob programmed with Eric, Joshua and Paul.
=> prevent promise return when callback provided

lib/refresh.coffee
This is a regression introduced when I reworked the set of promises returned when a page is built. New pages no longer have the ghost style applied to them.
This is error that appears in the console:
> client.max.js:4390 Uncaught (in promise) TypeError: Cannot read property 'addClass' of undefined
>    at client.max.js:4390
After the change, new pages again have the ghost style applied.
=> Fix error preventing ghost on new pages

lib/refresh.coffee
Treat remote pages as read-only when dragging. You cannot move items within them and dragging 
Prior to this change remote items could be modified which would result in the remote page being forked.
Render the lineup starting at the earlier of the original location or the new location.
When copying or moving an item, the rendering was broken if the copy or move was to a position more than one spot before the original location.
=> Fix issues with drag and drop.

lib/neighborhood.coffee, lib/siteAdapter.coffee
This extends the site adapter, to add `getIndex` to enable the serialized site index file to be fetched as text rather than converting it to javascript object.
This fixes an issue seen with sites that require login to view.
=> extend site adapter to add getIndex to get the serialized site index.

lib/drop.coffee, lib/factory.coffee, lib/image.coffee, scripts/squeeze-logic.coffee, scripts/squeeze-test.js
Work in Progress
This should be enough to drag image urls to a factory and get an Image item that cites the remote resource. We've resisted this before because the remote image can disappear. This is a step forward toward more advanced image handling.
Aside: I couldn't demonstrate even this much in my development environment. I'd love to pair in order to get past this inability.
Some further work we'd like to explore:
=> decode urls based on image sufix

client/style/print.css, client/style/style.css, lib/legacy.coffee, lib/neighborhood.coffee, lib/neighbors.coffee, lib/page.coffee, lib/refresh.coffee, lib/siteAdapter.coffee, lib/target.coffee, package.json
This PR adds backlinks to a wiki page. This relies on extra link information being in the sitemap, added by the changes in fed-wiki/wiki-server#161
Backlinks are added at the bottom of the wiki page, just above the journal if it is being shown, initially in a collapsed state:
This expands to show a collaborative link for the page linking, and flags for the sites the page with links was found on:
Clicking on the collaborative link in the list behaves exactly as if the link was within the page. Click on the flag will open page from the wiki that flag is for. 
Holding shift and hovering over the flag will highlight, and try to align, the page item containing the link. Just like it does with page items and journal items already.
A bug was discovered in the siteAdapter, where if there was an …
=> Add Backlinks and resolve a siteAdapter issue

lib/legacy.coffee, lib/link.coffee, lib/refresh.coffee
Prior to this change, doInternalLink() would receive a title or a slug, convert it to a slug, and call showPage() with the slug. refresh.cycle() would be invoked which resolved the slug back into a title. That particular flow would fail for clicks on the graphviz plugin.
This change lets the original title be passed through to createPage for the cases when we already know the intended title, like the graphviz case.
=> collaborative links now prefer the title

lib/refresh.coffee
Steps to replicate:
1. Have two pages open next to each other
2. Create a new paragraph in the first column
3. shift-click-drag the paragraph to the second column (to copy)
4. double-click the original paragraph and change the text
What I expect to happen:
1. Only the text in the first column changes
What actually happens:
1. The text changes in both columns (only in UI, if I refresh the page it corrects itself)
Resolution:
1. In `refresh.coffee` function `aliasItem` we are already cloning `oldItem` as `item` (via `$.extend`)
2. Assign this cloned `item` to `$item` via the data method (`$item.data('item', item')`)
=> Assign cloned item to  when aliasing to prevent undesired ui changes

lib/legacy.coffee
We have had a request for the ability to share a single wiki page with other federated wiki users. A suggested application what selectively sharing private pages via other file sharing such as email.
We note that the JSON link at the bottom of every page will respond favorably to the `Save Link As...` menu by writing a page-json page for any page visible to the current viewer, logged on or not.
This modification notices when a single page-json file has been dropped as if it were export json. We wrap the dropped page with another layer of object so that it falls into line with normal import. We also adjust the importer page synopsis to make it clear how the drop has been interpreted.
=> likely change for drop-import of single page-json file

lib/neighbors.coffee
Pages count was getting increased incorrectly each time the sitemap got updated - adding the number of pages in the origin site each time.
This change corrects that, by summing the number of pages from the sitemaps for the sites in the neighbourhood.
=> correctly count number of pages

lib/legacy.coffee
First step in lineup reconciliation when forking from history.
Here we update the url to remove the _rev suffix from the page that is now the current version.
=> update url on fork from history

lib/neighbors.coffee
The total number of pages gets recalculated triggered by the `new-neighbor-done` event. However, some neighbors might not be done yet so those will fail with a type error when trying to count the number of pages with `site.sitemap.length`.
In this change any site that are still in flight, `sitemapRequestInflight` is still `true`, are ignored. They will eventually get included as they complete and fire their own `new-neighbor-done` event.
=> ignore any sites with sitemap request still inflight when counting pages

lib/neighbors.coffee
At some point I there was the change from `totalPages += pageCount` on each sitemap load, which if I remember correctly was inflating the number. To doing the count across all the sitemaps from fresh each time, using `reduce()`. For whatever reason that reduce never added the number of pages in each wiki into the running total. 😊
=> remember to add number of pages to the running total

lib/importer.coffee, lib/search.coffee
adding a journal with a create actions to the search results allow a forked result page to be later removed.
=> give search results ghost a journal

lib/neighborhood.coffee, lib/neighbors.coffee, lib/util.coffee
Add a periodic refresh of sitemaps, if there have been any remote changes.
Add some extra information to the hover information on the flags in the neighbourhood bar.
The refresh interval depends on how long ago the sitemap was updated. The initial thought was that they should be checked as far in the future as they were last updated in the past, but limited to be no more than a day. This is probably too infrequent, so will most likely be reduced.
=> sitemap refresh

.github/workflows/tests.yml
`npm test` runs against the latest 2 node versions when PRs are opened.
While I do have a habit of running these locally, it's really nice to be able to see a passing test suite before jumping into code reviews.
Example test run:
https://github.com/heymatthew/wiki-client/actions/runs/3907659277
=> Use github actions to run tests on PRs

lib/plugin.coffee, lib/plugins.coffee
Add a mapping between old plugins and their successors.
There was a thought this functionality was previously included when the `federatedwiki` plugin was replaced by `reference` plugin. But, that seems to have been lost along the way.
Added to support the replacement of the implementation specific `mathjax` plugin with the `math` plugin.
=> Add plugin successor mapping

lib/neighbors.coffee
If the flag of a failed site is clicked on, in the neighbourhood bar, the site adapter will retest how to access that wiki.
However, when adding sitemap refresh the age of the sitemap, and refresh interval, was added to the flag's tooltip.
This update will not add that extra information, when the sitemap fails to load, but also filters it out to provide some extra protection.
=> fix issue with refreshing failed site

client/runtests.html
Found the reference to the old version of jQuery that was causing Dependabot to raise an alert. As the version of jQuery being referenced is not included here, so the real problem would be that `runtest.html` would not have worked.
=> update jquery version in runtest

lib/legacy.coffee, lib/neighborhood.coffee, lib/siteAdapter.coffee
Some changes related to Login to View.
Refactoring the sitemap handling to use siteAdapter, so we use its support for login to view, and adding support for returning lastModified date when returning sitemaps.
Adding 'login required' support for sitemaps - these will often be the second resource fetched from a remote wiki, after the flag.
=> Adding support for Login to View

lib/neighborhood.coffee
Addressing the ever spinning flag, caused by the data destructure failing, so the error handling is never reached.
Error message from console:
Uncaught TypeError: e is null
u client.max.js:1978
r client.max.js:5035
get client.max.js:5095
u client.max.js:1976
n client.max.js:2028
setTimeout handler*r client.max.js:2035
registerNeighbor client.max.js:2053
load_sites welcome-visitors line 2 > injectedScript:42
bind welcome-visitors line 2 > injectedScript:186
jQuery 2
=> Address the forever spinning flag when wiki is unreachable.

lib/refresh.coffee
Changes to allow items to be copied from a remote page with the same slug.
=> Copy is not the same as move!

lib/target.coffee
The comments on `target.coffee` mention
> Target handles hovers over items and actions. Other visible
items and actions with the same id will highlight. In some cases
an event is generated inviting other pages to scroll the item
into view. Target tracks hovering even when not requested so
that highlighting can be immediate when requested.
*Some cases* appears to be only while moving the mouse over an item while holding the shift key down.
The change here will amends the keydown event, start of requesting highlighting, to also trigger the event to scroll the item into view on other pages.
=> align items when starting targeting

lib/siteAdapter.coffee
As well as removing any subdomains, also remove any port before checking if the remote is a wiki on localhost.
=> fix: handle case when site has a port number in URL

client/style/style.css, lib/future.coffee, lib/resolve.coffee, test/wiki.coffee
Addressing an old usability trap (#284): internal links that start/end with spaces look much the same as one that doesn't, but creates a different name for the wiki page file.
[[space]] -> 'space',
[[ space]] -> '-space'
Simply trimming the space off of the internal link is not a solution, as it would leave those pages that already exist, with such names, as unreachable.
In this change we add some styling to highlight internal links that start/end with a space. <img width="490" alt="Screenshot 2024-02-19 at 10 49 06" src="https://github.com/fedwiki/wiki-client/assets/1552489/fe98cdbe-b30f-4fbd-b4b7-17ab38819700"> 
On the "_We could not find this page._" page, the create page line is replaced with a message. _A better message is needed._
=> Handle internal links that start/end with spaces

lib/search.coffee
The reference items on the search results ghost page were missing an itemId. This causes a problem elsewhere.
Thanks @dobbs for raising this during Sunday's call.
=> Add missing item id

Gruntfile.js, lib/plugin.coffee
I know it seems insane, but this seems to just work.
By using the built in import expression we can dynamically load scrips like we have been, but those scrips in turn can now use import statements and easily load their own dependencies without a build step. For a plugin that would often mean pulling from its own plugin folder like
```js
import { test } from '/plugins/mech/test.mjs'
```
The grunt change is required to prevent babel from replacing native dynamic imports with it's own stuff. This is the only call to loadScript so it was easy to cut the unused options argument, and convert the response to normal promise methods.
This is going to require a lot of testing.
=> Use dynamic import to load plugin client code

lib/neighborhood.coffee
A fix for incorrectly using the non-existent `item`, rather than `currentItem` in `extractPageText()`.
Causes the re-index after editing audio,frame or video items to fail and the client's index to fail.
=> Extract from currentItem, not item

lib/factory.js, lib/neighborhood.js, lib/page.js, lib/pageHandler.js, lib/refresh.js
The replacements for the _ functions aren't as general as what was there, but they all seem to suit our purposes.
Underscore is still used in the tests.
=> Remove underscore from the production client.

lib/search.js, lib/state.js
Not really so complex. Just made so by decaffeinate adding in a return when none was needed.
The standard `git diff` also makes it harder to see what is happening. So here is difftastic view of what I've done.
This section of code is adding highlighting to the search results, all DOM side effects, nothing to return to the caller.
=> Another DS205 down

.github/workflows/tests.yml, .gitignore, AUTHORS.txt, client/test/mocha.css, client/test/mocha.js, lib/drop.js, lib/link.js, lib/page.js, lib/refresh.js, package-lock.json, package.json, scripts/build-client.mjs, scripts/build-testclient.mjs, scripts/update-authors.js, test/page.js, test/pageHandler.js, testclient.js
This is a work in progress, commits are in bite sized chunks to help with explaining the changes.
Before replacing Grunt/Browserify build process, replace `Node:events` (f009685dfe7b850ed1d74f2dda8a7fcf95d6f52f) and `Node:url` (6afcaf0276ff88174bc7740f3e650546b00b1d2f) with their browser equivalents.
Update the node versions used in the test action, and modify `.gitignore`, pre-empting some of the changes happening next.  (930c000c731775646619fc43b3ee78569e90d5fd) and (db6301a11d7e84645c17d6d45f00e334344befd5)
=> Updating Decaffeinated Build

lib/legacy.js, lib/pageHandler.js
I don't know what I was thinking when I replaced a convoluted switch statement with a malformed table lookup.
This expression has been shown to work.
=> fix arrow keys and local storage

client/style/style.css, lib/active.js, lib/legacy.js
Replacing #327, which used the coffeescript, now legacy, branch as a starting point.
(cherry picked from commit fe55e8264bb73f4427c8ad60792d25b45ecc9585)
=> display flex for native scrolling

lib/active.js, lib/legacy.js, lib/siteAdapter.js, lib/target.js
Two fixes for old problems, and one from decaffeination.
1. Fixes some old targeting issues that were causing problems.
2. Adds a guard against missing title attributes, which can occur with malformed HTML/Markdown links.
3. Ensures that the `$.ajax` calls are returned when the caller could be using promises. *Discovered when using the graphviz plugin.*
---
This is **part 2 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #334 
- <kbd>&nbsp;2&nbsp;</kbd> #333 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #332
=> Some fixes

client/style/style.css
scale images height, rather than using the height of the unscaled image.
=> fix issue with image height scaling

lib/neighborhood.js, lib/neighbors.js
The changes in this commit add the ability to remove a wiki from the neighborhood.
- Adding an `evict` function that removes a wiki from the neighborhood by finding the corresponding DOM element and removing it, updating the `wiki.neighborhood` object, and triggering an update of the page count.
- Adding a new event handler for the `dragend` event on the neighborhood flags. Checks if the drag ended outside the window, or more than half way up the window, and calls `evict` to remove the wiki from the neighborhood.
=> add ability to remove a wiki from the neighborhood

lib/editor.js
Addressing an issue where item type changes, made via the ctrl/cmd+m shortcut, were not being saved unless the item content was also edited.
=> Improve handling of item type changes
