fedwiki/wiki-client

lib/factory.coffee

This replaces the slug that was lost last summer.
https://github.com/fedwiki/wiki-client/pull/81#issuecomment-68618526

lost slug on drop

---

lib/legacy.coffee
lib/page.coffee
lib/pageHandler.coffee
lib/refresh.coffee
lib/search.coffee

Reverts fedwiki/wiki-client#89 - small but persistent bugs are blocking this.

Revert "Improved put logic makes editing in localStorage viable."

---

lib/factory.coffee

Ward and team: This is unimportant, really just a way for me to test an aspect of GitHub for an article I am writing.

fix typo in comment

---

lib/wiki.coffee

so we can reuse search within the activity plugin - see fedwiki/wiki-plugin-activity#8

exposing `wiki.neighborhoodObject`

---

client.coffee

Remove a couple of parens on require expressions.

Don't use parens in require

---

client/style.css

This small change in style.css will allow a factory to grow vertically when there are more than the normal number of plugins in any one category.

Let factory grow vertically with lots of plugins.

---

views/static.html

This commit cascades theme content from an optional subdirectory, theme,  in the sites state subdirectory. This commit, coordinated with a companion commit in wiki-node-server, will allow a site administrator to configure custom css on a site by site basis. Future plugins might expose this capability to the site owners too.
See https://github.com/fedwiki/wiki-node-server/pull/105

cascade themes from the status directory

---

lib/legacy.coffee

use .find(...).length - true if something is found

---

Gruntfile.js
package.json

Adding 
* retire.js - to check for libraries with known security problems.
* nsp - to check for known vulnerabilities in node packages

Adding checks for vulnerabilities in libraries and node packages

---

lib/factory.coffee
lib/future.coffee
lib/image.coffee
lib/neighborhood.coffee
lib/neighbors.coffee
lib/pageHandler.coffee
lib/refresh.coffee

The start of making the client work over https
There are updates to a number of plugins that are part of this update.

use protocol-relative links when making requests - first pass

---

lib/legacy.coffee

This is a repeat of an addendum to #192 but requesting a merge with next, not master.

oops. forgot to press save on this last edit

---

lib/legacy.coffee

Fix for issue #199.
Look for _rev0 which shows that user really did click an action, not just that the ghost page has journal with only create.

detect delete based on _rev0

---

lib/editor.coffee

This is part of a re-look at the markdown plugin. Here we start to treat markdown items a bit more like paragraph items.
When editing a markdown item:
* pressing `enter` twice will save the current markdown item and create a new one. (this will also split a markdown item is the insertion point is not at the end of the item).
* pressing `backspace` at the start of a markdown item will append the current markdown item onto the previous page item, if it is also a markdown item.
**N.B.** this does not prevent a markdown item from containing more than block of markdown text.

split markdown items when enter is pressed twice

---

lib/editor.coffee

Discussed in https://github.com/fedwiki/wiki-client/pull/204#issuecomment-343762247

proper form for alternative

---

lib/siteAdapter.coffee

Companion to fedwiki/wiki-security-passportjs#18

add xhrFields for credentials

---

lib/siteAdapter.coffee

* rename the existing key store to "routes"
* add new store "withCredentials" for if credentials are required. value only stored when true.
Within the remote site get we split out the ajax `GET` and recursively call it when we get a "Login Required" response and have not already got `withCredentials: true` set.

modify siteAdapter to only send credentials when required

---

Gruntfile.js
package-lock.json
package.json

- update localforage
- remove nsp
- update coffeescript (switching from coffee-script to coffeescript packages)
- adding babel step to transpile the coffeescript output, needed for some browsers
- update other build packages
- add package-lock.json

Update build, reflecting package updates

---

lib/factory.coffee
lib/legacy.coffee

paired with @WardCunningham 
Information here: http://ward.asia.wiki.org/view/hamburger-menu

Add hamburger menu to open system links

---

lib/legacy.coffee

Paired on this with @wardcunningham

Convert Selected Plugin Pages to references with synopses

---

client/style/style.css
lib/active.coffee
lib/legacy.coffee
lib/search.coffee
lib/searchbox.coffee

Putting this up for review. Typing in the search box immediately runs a search. If the search returns multiple results, pressing enter will open a search results page. If there's only one, the single page in the results will be opened instead.
Work remaining:
* Tighten up a couple of CSS queries.
* Possibly tweak the styling.
* Perform more testing (need to test with search boxes on other pages open).

Initial implementation of incremental search

---

client/style/style.css
lib/active.coffee
lib/legacy.coffee
lib/neighborhood.coffee
lib/pageHandler.coffee
lib/search.coffee
lib/searchbox.coffee
package-lock.json
package.json

This builds on #258, working together with fedwiki/wiki-server#152 to add full text search for the neighbourhood. Here we are using [minisearch](https://github.com/lucaong/minisearch).
For full text search we rely on the server constructing an index and serializing it, so we can download it and load it in the browser. Where this index is not available we use the synopsis from the sitemap to construct an index for the wiki.
We then use the code from #258 to do an incremental search across this indexes, the results are sorted by rank for presentation.

Full text search

---

lib/search.coffee

Highlight the terms used in the progressive search, rather than just matching phrases.

Highlight search terms in results

---

lib/plugin.coffee

skip item being edited in renderFrom()

---

lib/neighborhood.coffee
lib/page.coffee

Update the client add some updates made on the server, so the sitemap and index in the current session reflect the changes made on the server.
* References are included in the links in the sitemap - fedwiki/wiki-server#169
* The URLs from external links are excluded from the text being indexed - fedwiki/wiki-server#170

Client updates

---

package-lock.json
package.json

This upgrade closes two dependabot alerts.

upgrade to mocha 9.2.1 & rebuild package-lock.json

---

lib/page.coffee

The client part of fedwiki/wiki-server#169
Include adding any reference links while we are updating the client-side version of the sitemap post edit.

References should be included in backlinks

---

lib/addToJournal.coffee
lib/legacy.coffee
lib/util.coffee

Old hover:
New hover:
Recompute time on each new hover.
We won't see actions claiming to have occurred milliseconds ago for long.

updated time on action hover

---

lib/neighborhood.coffee

Update the text extract logic to include better removal of markup tags. This mirrors the change made on the server in fedwiki/wiki-server#183

Update Text Extract For Indexing

---

lib/refresh.coffee

@nrn and I coded this duplication anticipating the day we drop jQuery.

duplicate pageKey in dom native data attribute

---

lib/neighborhood.coffee

use the same updated reducer as the server

Improving text index

---

lib/factory.js
lib/page.js
test/page.js

No longer extend neighborhood with reference items

---

lib/plugin.js

mitigate for issue in jquery ui with sortable with large number of items.

very large pages no longer freeze ui
